### ISSUE TITLE
Data access / Data portability to fix climate change

### ISSUE THREAD

**Issue by martincollignon** [opt-out-eu/opt-out#111]
We're building an app at tmrow.com that allows you to track your carbon emissions based on services and apps you already use. That means we already have integrations with Ryanair, Uber, Tripit, Tesla Cockpit, a utility in Denmark, the Oyster card equivalent in Denmark, and banks (through a PSDII API provider)- you can check most of our integrations [here](https://github.com/tmrowco/tmrowapp-contrib).

Our app is limited by the data that services provide to our users. Very important: we're not getting any of the data, as our app is private by design and the data stays on the device (unless the user decides to share that data with us). We will earn money on the corporate version of the app. 

I had the idea of using GDPR to let users get access to more of their own data, but we have very little experience and thus would love your input on what could be done, and if relevant, a potential partnership.

Would love to discuss and use your expertise to fix climate change!

**Comment by yoavaviram** [comment]
Hi @martincollignon, thanks for reaching out. The topic of client change is close to our harts, and we would love to help. Let's arrange a call sometime soon. Please contact me at yoav[at]opt-out.eu.

**Comment by yoavaviram** [comment]
Hi @martincollignon, thanks for reaching out. The topic of client change is close to our harts, and we would love to help. Let's arrange a call sometime soon. Please contact me at yoav[at]opt-out.eu.
