### ISSUE TITLE
[Thank You] social sharing image & description

### ISSUE THREAD

**Issue by yoavaviram** [opt-out-eu/opt-out#70]
LinkedIn, Twitter and FB sharing dialogs don’t show a picture or display a text. The copy for the text can be found here (under description/social): https://docs.google.com/document/d/1Pl02ycvvFB5PcAFm8Zc3lIkPH9qyImVti9pW038-9uU/edit#heading=h.gxb499se6mi0

**Comment by roughprada** [comment]
it shows it in facebook and LinkedIn to me, but now Twitter. Can you double check that?

**Comment by yoavaviram** [comment]
Works (i don't think twitter is supposed to show a picture)
