### ISSUE TITLE
Search result click event

### ISSUE THREAD

**Issue by yoavaviram** [opt-out-eu/opt-out#9]
I'm having a hard time setting up a GA event that triggers when a search result is clicked. The click event is sometimes registered on the <span>, and sometimes on the <img>, so I set up both. However there's also the case when a user clicks enter while typing or after using the arrows. Google tag manager does not have a simple way of capturing these. Can you help me simplify this? Since search is implemented as a form, can simply submit it to perform search?

**Comment by roughprada** [comment]
Any updates on this one?
